# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ffb872241291596a58ddab0efa2d626464dc23fc1e02920590942fbe9c2bf580625ab68b04ccc90cc9e76fd871cf6d6cb1d2bdce56f6515e8faa9b02f14f59f

test:
  secret_key_base: 9a8589d90eb621d284d7660f4a20a283dc224afacb6dfab0d10c3181f8cf102a1929ef23a618223d63102a5b0519925dd90d79750be588656af817ff1658b4ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
